CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users (id),
    title character varying NOT NULL,
    description text,
    due_date date,
    completed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow individual access to own tasks"
    ON tasks
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert of own tasks"
    ON tasks
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual update of own tasks"
    ON tasks
    FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Allow individual deletion of own tasks"
    ON tasks
    FOR DELETE
    USING (auth.uid() = user_id);
