// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sokxyczvmzriuccdvubm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNva3h5Y3p2bXpyaXVjY2R2dWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTI1MTUsImV4cCI6MjA2ODU4ODUxNX0.7s_9xPSmbk8ANB8_LSuxFlCx0KdJupVYiwVSz2PNTDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
